### ISSUE TITLE
AttributeError: DirectName_py.thomasa88lib has no attribute 'win'

### ISSUE THREAD

**Issue by bandesz** [thomasa88/DirectName#14]
I get the following error after I create e.g. a sketch:

```
DirectName error: module '__main__%2FUsers%2F<user>%2FLibrary%2FContainers%2Fcom_autodesk_mas_fusion360%2FData%2FLibrary%2FApplication%20Support%2FAutodesk%2FApplicationPlugins%2FDirectName_bundle%2FContents%2FDirectName_py.thomasa88lib' has no attribute 'win'

Copy this message by taking a screenshot. Describe what you did to get this error or record a video.

--------------------------------------------------

Fusion 360 v. 2.0.20508
/Users/<user>/Library/Containers/com.autodesk.mas.fusion360/Data/Library/Application Support/Autodesk/ApplicationPlugins/DirectName.bundle/Contents/thomasa88lib/events.py failed: 

Traceback (most recent call last):
  File "/Users/<user>/Library/Containers/com.autodesk.mas.fusion360/Data/Library/Application Support/Autodesk/ApplicationPlugins/DirectName.bundle/Contents/thomasa88lib/events.py", line 142, in catcher
    func(args)
  File "/Users/<user>/Library/Containers/com.autodesk.mas.fusion360/Data/Library/Application Support/Autodesk/ApplicationPlugins/DirectName.bundle/Contents/DirectName.py", line 353, in rename_command_created_handler
    auto_focused = press_tab()
                  ^^^^^^^^^^^
  File "/Users/<user>/Library/Containers/com.autodesk.mas.fusion360/Data/Library/Application Support/Autodesk/ApplicationPlugins/DirectName.bundle/Contents/DirectName.py", line 394, in press_tab
    return press_key(thomasa88lib.win.input.VK_TAB, times)
                     ^^^^^^^^^^^^^^^^
AttributeError: module '__main__%2FUsers%2F<user>%2FLibrary%2FContainers%2Fcom_autodesk_mas_fusion360%2FData%2FLibrary%2FApplication%20Support%2FAutodesk%2FApplicationPlugins%2FDirectName_bundle%2FContents%2FDirectName_py.thomasa88lib' has no attribute 'win'
```

If it matters:
```
$ python3 --version
Python 3.13.0
```

OS: macOS Sonoma 14.6.1

**Comment by bandesz** [comment]
This is causing the issue, `press_tab` is called in `rename_command_created_handler` without checking the OS. 

```
def press_tab(times=1):
    return press_key(thomasa88lib.win.input.VK_TAB, times)
```

E.g. this solves it:
```
def press_tab(times=1):
    if IS_WINDOWS:
        return press_key(thomasa88lib.win.input.VK_TAB, times)
    return False
```

**Comment by thomasa88** [comment]
Thanks for reporting this. I had a hackintosh at one point to test on, but it's now out of comission.

And ah, it is the import that is not loaded for Mac, of course..

I ended up using your suggested solution. I will submit the update to Autodesk.
