### ISSUE TITLE
[Windows 10] RuntimeError: 2 : InternalValidationError : selecCmd

### ISSUE THREAD

**Issue by jaddel** [thomasa88/DirectName#7]
```
Copy this message using Ctrl+C:

C:\Users\Max\AppData\Roaming\Autodesk\ApplicationPlugins\DirectName.bundle\Contents\thomasa88lib\events.py failed:

Traceback (most recent call last):
  File "C:\Users/Max/AppData/Roaming/Autodesk/ApplicationPlugins/DirectName.bundle/Contents\thomasa88lib\events.py", line 142, in catcher
    func(args)
  File "C:/Users/Max/AppData/Roaming/Autodesk/ApplicationPlugins/DirectName.bundle/Contents/DirectName.py", line 358, in rename_command_input_changed_handler
    focus_changed(args.input)
  File "C:/Users/Max/AppData/Roaming/Autodesk/ApplicationPlugins/DirectName.bundle/Contents/DirectName.py", line 369, in focus_changed
    ui_.activeSelections.clear()
  File "C:\Users/Max/AppData/Local/Autodesk/webdeploy/production/df098dc22bdb0532c3884db0a2d6182c8f8678de/Api/Python/packages\adsk\core.py", line 15655, in clear
    return _core.Selections_clear(self)
RuntimeError: 2 : InternalValidationError : selecCmd
```

Hi, thanks for the great plugin. I just redownloaded the plugin after a while and I'm getting this error. Do you have a suggestion how to fix this?

**Comment by Pixel48** [comment]
I have encountered the same issue. In my understanding, it is related to a part of Fusion 360's API that is responsible for focusing text boxes and widgets, but I have not yet found a solution to this problem

**Comment by patl1** [comment]
Thomas, remind me what I need to do to patch the add-in with your changes. Thanks

**Comment by ah3243** [comment]
I've got the same problem on mac, with these details: 
Fusion 360 2.0.15775 x86_64 [Rosetta 2] 
macOS 13.1 (22C65) on MacBookPro18,3

**Comment by thomasa88** [comment]
Closing duplicate. Follow in #5 .
