### ISSUE TITLE
Error Prompt - RunTimeError: 2- Message DirectName v1.2

### ISSUE THREAD

**Issue by kmbrady** [thomasa88/DirectName#9]
Getting the error message posted below when entering a name in the DirectName pop-up box name field. Additionally, when pressing the Set Name button. The error message window opens, I press OK on the error popup and the DirecrName tool works as designed, just the error message is popping up each time. I'm using the April 2023 F360 release 
++++++++++++
-------------------------------------------- Error Message Text -------------
---------------------------
Fusion 360
---------------------------
Copy this message using Ctrl+C:

C:\Users\kmbra\AppData\Roaming\Autodesk\ApplicationPlugins\DirectName.bundle\Contents\thomasa88lib\events.py failed:

Traceback (most recent call last):
  File "C:\Users/kmbra/AppData/Roaming/Autodesk/ApplicationPlugins/DirectName.bundle/Contents\thomasa88lib\events.py", line 142, in catcher
    func(args)
  File "C:/Users/kmbra/AppData/Roaming/Autodesk/ApplicationPlugins/DirectName.bundle/Contents/DirectName.py", line 358, in rename_command_input_changed_handler
    focus_changed(args.input)
  File "C:/Users/kmbra/AppData/Roaming/Autodesk/ApplicationPlugins/DirectName.bundle/Contents/DirectName.py", line 369, in focus_changed
    ui_.activeSelections.clear()
  File "C:\Users/kmbra/AppData/Local/Autodesk/webdeploy/production/22e664d43fce268ac9bf1fa1cda69e4a9585c997/Api/Python/packages\adsk\core.py", line 15655, in clear
    return _core.Selections_clear(self)
RuntimeError: 2 : InternalValidationError : selecCmd

---------------------------
OK   
---------------------------

**Comment by thomasa88** [comment]
Hi, thanks for the detailed error description.

I believe that it should be fixed in version 1.2.2.

Please see this message on how to get the new version before it has been approved by the Autodesk store:
https://github.com/thomasa88/DirectName/issues/5#issuecomment-1507468537

**Comment by kmbrady** [comment]
New version resoled the issue. Thanks, really love the tool
